### ISSUE TITLE
Cahpter 6: this.playSound is not a function

### ISSUE THREAD

**Issue by Frozenfire92** [rezoner/unfinished-asteroids#4]
I have loaded the sounds using `this.loadSounds()` in App.js but when I go to call `this.playSound("shoot");` in Player.js I get the following console error

```
TypeError: this.playSound is not a function
```

**Comment by dub4u** [comment]
Because `this` in Player.js refers to the Player instance. You need to use `app.playSound("shoot")`

**Comment by Frozenfire92** [comment]
Literally just tried that :smile:

Thanks!
