### ISSUE TITLE
Chapter 7 (Score) - How to access player entity

### ISSUE THREAD

**Issue by tobipch** [rezoner/unfinished-asteroids#5]
Hello :)

I have a question about how I could access the player who shot the asteroid from Asteroid.js (hit function). Is there something I can do over app.?

Thank you

**Comment by rezoner** [comment]
Wow, I quite overlooked this - we will have to make a task out of it so everyone have this working :)

**do:** Go to `Player.js` and find `shoot` method - among the arguments passed to the new bullet add `parent: this` - so a bullet can tell who shoot him

**why:** As you can see - when bullet hits something it is calling `entity.hit(this)` so it passes itself as an argument.

**result:** With point 1 fulfilled you should be able to access `data.parent` in `hit` method << also you can rename `data` to `bullet` if you find it more convenient :)

**Comment by byFd** [comment]
I used the team property of the bullet to access the player. Something along the lines of `app.game.players[data.team].score += 1`. Not sure if this is good code, but it works.

**Comment by rezoner** [comment]
@byFd: if it works - it is good :+1: 

Can be troublesome later - when we add some shooting enemies tho - but I am sure you will easily find the solution.

**Comment by tobipch** [comment]
@rezoner Your first answer worked perfectly for me, thanks very much!
